<?php
declare(strict_types=1);

return [
    'name' => getenv('APP_NAME') ?: 'Anonymous Feedback Tool',
    'base_url' => getenv('APP_BASE_URL') ?: 'http://localhost:8000',
    'hr_auth_mode' => getenv('HR_AUTH_MODE') ?: 'hybrid',
    'ldap_host' => getenv('LDAP_HOST') ?: 'localhost',
    'ldap_port' => (int) (getenv('LDAP_PORT') ?: 389),
    'ldap_base_dn' => getenv('LDAP_BASE_DN') ?: '',
    'ldap_domain' => getenv('LDAP_DOMAIN') ?: '',
    'ldap_bind_pattern' => getenv('LDAP_BIND_PATTERN') ?: '%s',
    'ldap_service_user' => getenv('LDAP_SERVICE_USER') ?: '',
    'ldap_service_password' => getenv('LDAP_SERVICE_PASSWORD') ?: '',
    'ldap_use_tls' => filter_var(getenv('LDAP_USE_TLS') ?: 'false', FILTER_VALIDATE_BOOLEAN),
    'ldap_hr_groups'      => getenv('LDAP_HR_GROUPS') ?: '',
    'ldap_is_groups'      => getenv('LDAP_IS_GROUPS') ?: '',
    'ldap_hr_ous'         => getenv('LDAP_HR_OUS') ?: '',
    'ldap_is_ous'         => getenv('LDAP_IS_OUS') ?: '',
    'ldap_hr_departments' => getenv('LDAP_HR_DEPARTMENTS') ?: '',
    'ldap_is_departments' => getenv('LDAP_IS_DEPARTMENTS') ?: '',
    'developer_override_users' => getenv('DEVELOPER_OVERRIDE_USERS') ?: '',
    'mailer_from' => getenv('MAIL_FROM') ?: 'noreply@localhost',
    'mailer_from_name' => getenv('MAIL_FROM_NAME') ?: 'Voice Without Fear',
    'smtp_host' => getenv('SMTP_HOST') ?: 'localhost',
    'smtp_port' => (int) (getenv('SMTP_PORT') ?: 587),
    'smtp_username' => getenv('SMTP_USERNAME') ?: '',
    'smtp_password' => getenv('SMTP_PASSWORD') ?: '',
    'hr_notification_email' => getenv('HR_NOTIFICATION_EMAIL') ?: '',
    'ethics_notification_email' => getenv('ETHICS_NOTIFICATION_EMAIL') ?: '',
    'notifications_immediate_enabled' => filter_var(getenv('NOTIFICATIONS_IMMEDIATE_ENABLED') ?: 'true', FILTER_VALIDATE_BOOLEAN),
    'notifications_scheduled_enabled' => filter_var(getenv('NOTIFICATIONS_SCHEDULED_ENABLED') ?: 'true', FILTER_VALIDATE_BOOLEAN),
];
